settings:
  legacy:
    force: false
    interval: 0s
  resources:
    outputs: outputs.log
    logs: logs.log
    errors: errors.log
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: app
  path: .
  commands:
    fmt:
      status: true
    install:
      status: false
      method: go build -o ./go-echo-api
    run:
      status: true
      method: ./go-echo-api
  watcher:
    extensions:
      - go
    paths:
      - /
    ignored_paths:
      - .git
      - .realize
      - vendor
