version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/go/src/app:cached
    ports:
      - "1323:1323"
    working_dir: /go/src/app
    tty: yes
    depends_on:
      - db
      - kvs

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: go-example
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: go-example
      MYSQL_PASSWORD: go-example
    volumes:
      - db-data:/var/lib/mysql:cached

  kvs:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-data: